### ISSUE TITLE
Default to no styling on ads

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-ads-component#28]
seems odd to have to overwrite almost all the `.advertising` styling on the ads on next-grumman.

can the default ad be unstyled and where we need things like margins, box shadows to be reusable we use BEM? e.g. `.next-ads-component--padded`

**Comment by matthew-andrews** [comment]
see #29

**Comment by aintgoin2goa** [comment]
Yes, all ad stuff is going to be removed out of the apps and placed into ads-component.  Then all this stuff will go into the component in a more sensible way

**Comment by robin-marr-ft** [comment]
@matthew-andrews is this still relevant?

**Comment by leggsimon** [comment]
@matthew-andrews @robin-marr-ft I guess this can be closed now? Unless there was anything further?

**Comment by matthew-andrews** [comment]
this seems super old
