### ISSUE TITLE
sometimes <link> not found

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-ads-component#35]
This is using the link tag to identify the app, which sometimes causes this: https://app.getsentry.com/nextftcom/ft-next-frontend/group/56122934/.

It's a bit weird that the bug ever happens, but should probably have a more robust way of identifying the app anyway. Maybe a data-attribute on the html tag added in next express?

@aintgoin2goa

**Comment by robin-marr-ft** [comment]
@wheresrhys There is now a data attribute on the html tag and we use that, can I close this?

**Comment by wheresrhys** [comment]
yep
